# Generated by Django 5.1.1 on 2024-12-14 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='MovieInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bus_name', models.CharField(max_length=255)),
                ('Bus_number', models.IntegerField(null=True)),
                ('Bus_root', models.TextField()),
                ('Bus_image', models.ImageField(null=True, upload_to='images/')),
                ('Bus_owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='OwnerOfBus', to='Bus_root.owner')),
            ],
        ),
    ]
