# Generated by Django 5.1.1 on 2024-12-14 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bus_root', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieinfo',
            name='Bus_owner',
            field=models.CharField(max_length=255),
        ),
    ]
