# Generated by Django 5.1.1 on 2024-12-14 10:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bus_root', '0003_delete_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieinfo',
            name='Bus_time',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
